URL_DATABASE: 'postgresql://santiago:santiago@localhost:5432'
URL_API: 'http://127.0.0.1:8010/TODOREPUESTOS/search'
# URL_API: 'http://161.18.230.181:8010/TODOREPUESTOS/search'

DATABASES:
  - name: "TODOREP2"
    models: 
      - "stock_move_ia"

  # - name: "DATABASENAME"
  #   models: 
  #     - "other_model"
      